;;; Automatically generated by ‘recentf’ on Wed Jun 28 14:56:01 2023.

(setq recentf-list
      '(
        "~/.emacs.d/configs/tmnt_theme_color.el"
        "~/.emacs.d/donatello-theme_and_config.el"
        "~/.emacs.d/init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
