;;; Automatically generated by ‘recentf’ on Mon Aug 28 12:04:55 2023.

(setq recentf-list
      '(
        "~/.emacs.d/init.el"
        "d:/intern/dev/MiniTodo/Program.cs"
        "d:/intern/dev/MiniTodo/Models/Todo.cs"
        "~/.emacs.d/configs/fonts.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
